name: huskkk
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.11.0
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.0.0
  flutter_switch: ^0.3.2
  fluttertoast: ^8.2.2
  firebase_core: ^2.18.0
  cloud_firestore_web: ^3.8.0
  firebase_storage: ^11.3.0
  cloud_firestore: ^4.10.0
  uuid: ^3.0.7
  contacts_service: ^0.6.3
  permission_handler: ^11.0.1
  firebase_database: ^10.3.0
  intl: ^0.18.1
  zego_uikit_prebuilt_call: ^3.7.1
  zego_express_engine: ^3.10.0
  agora_rtc_engine: ^6.2.1  
  firebase_messaging: ^14.6.4
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/Husklogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
