name: huskkk
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: any
  flutter_speed_dial: any
  image_picker: any
  flutter_switch: any
  fluttertoast: any
  firebase_core: any
  cloud_firestore_web: any
  firebase_storage: any
  cloud_firestore: any
  uuid: any
  contacts_service: any
  permission_handler: any
  firebase_database: any
  intl: any
  zego_uikit_prebuilt_call: any
  zego_express_engine: any
  agora_rtc_engine: any
  cupertino_icons: any
  flutter_local_notifications: any
  firebase_messaging: any
  http: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/Husklogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
